version: 1.0.{build}

image: Visual Studio 2019 Preview

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true
clone_folder: C:\Projects\Frostbyte

skip_commits:
  message: /Update/

before_build:
  - cmd: dotnet restore
    
build:
  parallel: true
  verbosity: minimal

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/Yucked/Krypts/master/VeyorHook.ps1 -o VeyorHook.ps1
  - ps: ./VeyorHook.ps1 success $env:WEBHOOK_URL

on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/Yucked/Krypts/master/VeyorHook.ps1 -o VeyorHook.ps1
  - ps: ./VeyorHook.ps1 failure $env:WEBHOOK_URL